### PR TITLE
Default configuration file

### PR DESCRIPTION
**Pull request by mdaskalov**

### CODE REVIEW

**Comment by zirnipa** [comment]
OK

**Comment by stefanpolzer** [comment]
I would be careful with removing the config file!
If you have no config.php than all default Values are invalid!

**Comment by zirnipa** [comment]
@stefanpolzer 
We are renaming the config.php to sample-config.php.

This step is needed for putting the config.php on the git-ignore list.

**Comment by mdaskalov** [comment]
I agree with @stefanpolzer about renaming the config.php file. 
Have just seen, that the default values are used in the Mpay24Config initialisation.

**Comment by stefanpolzer** [comment]
I got that. But why is it necessary? The config.php file is required for the Class Mpay24Config to work.
So everyone has to rename it anyhow. So this has a bad impact on the end-user experience.

**Comment by stefanpolzer** [comment]
BTW: the config.php was once a Backward compatibility requirement. Is this now obsolete?

**Comment by stefanpolzer** [comment]
I agree that potential sensitive data should not be include in a distribution, but because the `config.php` is just the default for the Mpay24Config Class, and sensible date could be also set in other ways like using the constructor of the Mpay24 Class `new Mpay24('9****', '*********');` or the Mpay24Config Class itself, I would rather let the user of the package decide if he wants to remove the `config.php` file from his distribution. I believe most of the user do not chance the `config.php` file at all, if they used in composer context, and this is what most likely the majority do these days, right?

**Pull request closed without merging**
