### PR TITLE
Undefined varibale $name in Mpay24Order.php line 75

### LINKED ISSUE #71: Undefined varibale $name in Mpay24Order.php line 75

### PR DESCRIPTION
**Pull request by schoradt**
Fixes #71 and also add an initialization for $matches.

### CODE REVIEW

**Comment by zirnipa** [comment]
OK

**Comment by stefanpolzer** [comment]
This will fix #78 please merge to master branch!

**Comment by vedtam** [comment]
After applying the fix for the `$name` variable suggested @schoradt I got a step forward, but there is still an issue with: Street, Zip, City, Country. If I fill any of these variables Laravel throws like:

> The schema you have created is not valid!<br><br>Element 'Street': This element is not expected.<br>

screen shot 2018-03-18 at 10 19 56

**Comment by zirnipa** [comment]
@vedtam You need to provide the elements in the correct order:

```
$mdxi->Order->BillingAddr->setMode("ReadOnly");
$mdxi->Order->BillingAddr->Name = "Max Musterman";
$mdxi->Order->BillingAddr->Street = "Teststreet 1";
$mdxi->Order->BillingAddr->Street2 = "Teststreet 2";
$mdxi->Order->BillingAddr->Zip = "1010";
$mdxi->Order->BillingAddr->City = "Wien";
$mdxi->Order->BillingAddr->Country->setCode("AT");
$mdxi->Order->BillingAddr->Email = "a.b@c.de";
```

See: https://docs.mpay24.com/docs/mdxi-xml#section-addresstype

regards,
Patrick

**Comment by vedtam** [comment]
@zirnipa thanks! Jeeez, I have scanned the docs all day long but saw nowhere a word regarding the order, or is it there (if not present, it may be really helpful to include for others)?

**Pull request merged**
