### PR TITLE
Update required PHP version to meet actual requirements.

### LINKED ISSUE #58: PHP Version 5.3.8 - Parse error: syntax error, unexpected '['
Tested our SDK with PHP Version 5.3.8:
It looks like this PHP version does not support the used array declaration

public function token($paymentType, array $additional = [])
public function createTokenPayment($pType, array $additional = [])
public function acceptPayment($type, $tid, $payment = [], $additional = [])

Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\sdk\src\Mpay24.php on line 189

I think we should only support the supported versions: http://php.net/supported-versions.php

### PR DESCRIPTION
**Pull request by chesio**
Fixes #58.

### CODE REVIEW

**Comment by mdaskalov** [comment]
Thx chesio. 
Do you think it will work with 5.4? The travis build file includes 5.4, 5.6 and 7.0 and the build goes trough.

**Comment by chesio** [comment]
I guess the build passes, because test suite currently does not cover `\Mpay24\Mpay24Confirmation` class, where the PHP 5.6+ constructs are present. Try adding some tests for this class and see what happens.

**Comment by stefanpolzer** [comment]
@mdaskalov why you want to maintain unsupported PHP versions? PHP 5.6 and and 7.0 are EOL since last Month. PHP 5.5 is EOL since 2016 and PHP 5.4 since 2015 I guess. If someone still uses PHP 5.4, I assume he will also not update the mpay24-php package. On the other hand, if someone staring a new Project it will properly be with PHP 7.2 or PHP 7.3, right? The new versions also have no big benefit from a functional point of view. So if someone is using an older package of mpay24-php there is no disadvantaged because all features that someone uses are continue to working. From a security point of view: with older PHP versions there are quite a lot issues. Because this is a package that is related to Money transaction it would be a wise signal to say: "We care about security, therefore we do not support older PHP versions, but if you have to use a older PHP version you sill can use an older version that have all (or almost all) features included", or did I miss something that prevents you from stopping the support for PHP 5.5 or older?

**Comment by zirnipa** [comment]
@mdaskalov Please set the requirements to php >= 7.2

**Comment by TheLevti** [comment]
At minimum 7.1

Everything below reached end of life. Also with 7.1+ we can have all the nice things php currently offers (type hints, ...).

I would also suggest 7.2.

**Comment by stefanpolzer** [comment]
@zirnipa can you close this PR? A similar code is in the merged PR #90

**Pull request closed without merging**
