### PR TITLE
Implementing Request #18 & #19 and some enhancements

### PR DESCRIPTION
**Pull request by stefanpolzer**
Implementing Request https://github.com/mpay24/mpay24-php/issues/18 & https://github.com/mpay24/mpay24-php/issues/19 and some enhancements

If you take this PR than your Customers have multiple Options to use the Package
1) as it was with a config.php file (BTW at the moment this is completely removed)

2) Creating a Config Object (MPay24Config)
Per default everything will be taken from the config.php file.
But you have Setter-Methods to change any value or get the Values with the Getter.

One remark ProxyHost & ProxyPrort are only returned by the Getter if both are set.
The Same is true for ProxyUser and ProxyPassword

3) You can handover the Parameters to the constructor of the Configure Object or the  MPAY24 Class as you had it before.

This will look like e.g.:
```
$config = new MPay24Config('91234', 'abcdefghijk', true, true);
$mpay24 = new MPAY24($config);
```
Or in on line if you don't need to change any thing later:
`$mpay24 = new MPAY24('91234', 'abcdefghijk', true, true);`

Log file path can now be set with the setLogPath() Method e.g.:

```
$config = new MPay24Config('91234', 'abcdefghijk', true, true);
$config->setLogPath('/absolute/path/to/log/dir');

$mpay24 = new MPAY24($config);
```
All other Settings are documentet in the Readme...

### CODE REVIEW

**Comment by stefanpolzer** [comment]
This is a good Base to create a own Laravel Project that is using this Package as a base
If you want create a mpay24-laravel Project I'm going to do the basic work that you could use....

**Comment by tobiaslins** [comment]
Thanks @stefanpolzer !
We are going to discuss the mpay24-laravel project internally.
But great work so far!

**Comment by netbull** [comment]
@stefanpolzer is there a reason to implement MPay24Config object and remove the standard parameters from the MPAY24 object?

**Comment by stefanpolzer** [comment]
@netbull, ... you still have the possibiltiy to do it with standard arguments  (it's not Code hinted in the IDE I know ;-) ). But:
`$mpay24 = new MPAY24(91233, ******, true, false);`
still works !!!!!!

And:
```
$config = new MPay24();

$config->setMerchantID('91234');
$config->setSoapPassword('*******');
$config->useTestSystem(true);
$config->setDebug(true);

$mpay24 = new MPAY24(config);
```
Also works !!!!!

**Pull request merged**
