### PR TITLE
Remove mdxi validation

### PR DESCRIPTION
**Pull request by mdaskalov**
Simplified parsing of the SelectPayment response: closes #89 and #90

### CODE REVIEW

**Comment by zirnipa** [comment]
Please implement a proper error handling.
Currently a rejected request shows an empty page and no error is written in the log file.

e.g.:
`<etp:SelectPaymentResponse xmlns:etp="https://www.mpay24.com/soap/etp/1.5/ETP.wsdl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="etp:SelectPaymentResponse">
  <status>ERROR</status>
  <returnCode>INVALID_MDXI</returnCode>
  <errNo>13</errNo>
  <errText>Invalid MDXI: ERROR-1824: noname.xml:4: element Price: SchemasValidation: Element 'Price': '100a' is not a valid value of the atomic type 'PriceType'.</errText>
  <location/>
</etp:SelectPaymentResponse>`

**Comment by stefanpolzer** [comment]
@mdaskalov  this PR will have backward compatibility issue! If you delete the validation than every project that is using the **public** method Mpay24Order::validate() will beak! The best way is to mark it first as depricatdet an in the next mayor release e.g. 5.0.0 we delete it announced.

Second, there are some code elements that are not 100% right from my point of view:
keep the __construct() method as it is, because the hasNoError() method is checking for general errors (e.g. authorization, ...)
so if a geneal error is present wen can't parse the response body anyway. To avoid unexpected behavior we should do this check in the constructor, right?

Using the AbstractPaymentResponse Class seams to be a good idea but the SelectPayment do not have a MpayTid,
so using the wrong inheritance will end up with a object what have a method the will return null and leads to confusion.

My point is a object should mirror the attributes and methods that reflects the real response.
This could confuse other developers that are not so deep in this topic and may exact the TID, than open a issue and we have to  make a remark in the documentation and so on ... you get the point!

**Comment by mdaskalov** [comment]
@stefanpolzer: I agree about `Mpay24Order::validate()`. We decided to release 4.3.2 now and then in 5.0 to  support only PHP 7.2+ and drop `validate()`. 

Correct me if I didn't understood it right, but in my opinion with having `hasNoError()` check in the constructor the fields `errNo` and `errText` are never set, since they are returned only if the status is `ERROR`. But in this case `hasNoError()` returns false and `parseResponse()` is not called.

I also agree on the argument for using `AbstractPaymentResponse` class. Maybe we should create another class with no `MpayTid` and `Location` but having `errNo` and `errText` instead. Then we can add `MpayTid`, `Location`, etc. as needed.

**Comment by stefanpolzer** [comment]
@mdaskalov you have a point, but the `hasNoError()` do not reflect if the error is a general on e.g. "401 Unauthorized" where the `parseResponse()` methode may be failing and therefor a `Exception` will be thrown and the hole PHP process is crashing, or an more specific one where we can parse the XML response and read the `errNo `and `errText`.

So from my point of view we should refactor some of the code so that we can distinguish between those two cases.

I could check this but I would write the code fore PHP 7.2+ if this is ok with you.

**Comment by stefanpolzer** [comment]
@mdaskalov you don't need to remove any attribute/method form the `AbrstactPaymentResponse` Class. The Abstract Class is perfect for AcceptPaymentResponse and `ManualCallbackResponse` but sadly not for `SelectPaymentResponse` therefor this class need its own implementation because it is the only one with this list of response fields. Just reverse this commit https://github.com/mpay24/mpay24-php/pull/91/commits/314c332e028f862a66b425c4c08f90df61f38c98 and you are fine with this class ... PR https://github.com/mpay24/mpay24-php/pull/91 has now everything includes ... if you need a version for PHP 5.3+ than you could build a different tree from that?

**Comment by mdaskalov** [comment]
OK, I made it simple: rollback and then just removed the MDXI validation without changing anything else. If it's ok for you @zirnipa I will merge and make a new release. Then we will go for 5.0.

I don't think we will need a separate branch. This will be the last release to support PHP 5.3+ and that's it.

**Pull request merged**
