### PR TITLE
PSR-1 & PSR-2 and refactoring Response Classes

### PR DESCRIPTION
**Pull request by stefanpolzer**
To be hones I only want to Fix the PSR-1 & PSR-2 (Issue https://github.com/mpay24/mpay24-php/issues/40) for myself, but than I figured out that there are some issues wit the Response Classes.

Now they are using Class inheritance as it should be.
Every Response is now available thru the respective method. No Cascading
```php
$result->generalResponse->status;
```
just
```php
$result->getStatus();
```
For those how are interested: before my IDE was blinking like a Christmas tree,
now it is almost satisfied. No unknown Methods or Attributes and now other Warnings.

There is only one exception: the manualCallback() Method in Mpay24Soap Class.
BTW: The MPAY24 Class in now only a alias class

### CODE REVIEW

**Comment by tobiaslins** [comment]
@stefanpolzer we very much appreciate your work!
Thank you again for contributing

**Comment by netbull** [comment]
OMG?! This PR breaks everything... @stefanpolzer please stop ruining the code. 

- why you changed the namespace
- why you deprecated the MPAY24 class for god sake..
- if you want a wrapper class build it in your own app man, the SDK repo is not the place for that!

**Comment by tobiaslins** [comment]
@netbull 
* I would use the old class name again `Mpay24` instead of `Mpay24Soap`. Do you agree with this?

**Comment by netbull** [comment]
@tobiaslins the problem is not in what fits my app or @stefanpolzer's app. I work in a way to make changes very easy, but please consider to establish some ground rules how should we contribute to the SDK in order to evolve in a good way and avoid every developer to do what we want and what our apps require.

**Comment by tobiaslins** [comment]
@netbull 
I think we currently try to refactor the whole project. This branch is currently not a one to use for production.
We will also change all public method names as mentioned in #42 .
Since this will be a complete "rewrite" and new major release.

If this changes are merged to our master, we don't allow such changes anymore & will probably create a contribution guide

**Comment by netbull** [comment]
ok, but in my case I started the entire PSR4 saga, because the SDK didn't work well with composer, then I offered some changes to improve the usability of the SDK they were refused due to backwards compatibility issues and how we went to complete rewrite of the SDK.

Can I ask then when is expected to release the new version?

**Comment by tobiaslins** [comment]
@netbull 
I am really sorry for this!

I am currently changing all method names to our new definition, do some final testing and hope that we can publish it soon.

**Comment by stefanpolzer** [comment]
@tobiaslins @netbull Sorry for any inconvenience with this PR.

PSR dose mean PHP Standard Recommendation nothing more and nothing less.

PSR-1 and PSR-2 are accept by the PHP community and any International PHP project, as far as I know, follows this.
BTW PSR-12 is in draft and will replace PSR-2 one day or the other, and I try to apply this as good as possible.

After changing the Code to PSR-1 and PSR-2 I figured out that the new Response Classes did not follow the Concept of inheritance and polymorphism that is the base of OOP.

If class A is extending class B you do not need to create a new instance of B you are as good as B and can adapt or extend your functionality.

So this is absolutely against any OOP rules:
 
```php
class ListPaymentMethodsResponse extends GeneralResponse
{
    /**
     * An object, that represents the basic values from the response from mPAY24: status and return code
     *
     * @var string
     */
    var $generalResponse;

    function __construct( $response ) {
        $this->generalResponse = new GeneralResponse($response);
    }
}
```
So if you relay want to have this kind of Call back
```php
$result->generalResponse->status;
```
 it is possible to apply it to the new structure, but the last version was not correct.

**About Naming Conventions:**
Classes with only UPERCASE and name spaces that are not following the `StudlyCaps`, refers in PSR-12 as 'PascalCase' what is more accurate, is very unconventional.

As far as I understand there are 3 Method to interact with the mPAY24 Server

1. SOAP
2. HTML
3. FlexLink that is maybe a part of HTML
so having having Calsse Called `Mpay24Soap`, `Mpay24FlexLink` and maybe on Day `Mpay24Html' makes more sense to me than 'MPAY24'

I also do not know any good Project where the name space start with a lower case letter

**Pull request merged**
