### PR TITLE
Fixing borken methodes: manualClear, manualCredit, cancelTransaction

### PR DESCRIPTION
**Pull request by stefanpolzer**
Fix for most of Issue https://github.com/mpay24/mpay24-php/issues/37
I could not fix manualCallback and selectPayment is still only working the half way

This Line in manualCallback  do not work because the method do not exist (before it was not implemented)
```php
$order = $this->createFinishExpressCheckoutOrder($transaction, $shippingCosts, $amount, $cancel);
```
I also could only test manualCredit at the moment
You also want to check if it is good idea to use the TID as reference and not the mPAY24TID

### CODE REVIEW

**Comment by stefanpolzer** [comment]
Fix for most of Issue https://github.com/mpay24/mpay24-php/issues/37
I could not fix manualCallback and selectPayment is still only working the half way

**Comment by stefanpolzer** [comment]
@tobiaslins BTW: do you have a Coding Style for PHP Storm?
I use a little bit different one and that makes me crazy at the moment

**Comment by stefanpolzer** [comment]
Could Test selectPayment successful.
It's not good documented how to set it up => update read me and example file

**Comment by stefanpolzer** [comment]
@tobiaslins I added a new Class to validate the Get Parameter that append to the confirmation URL by mPay24:

Using it, is simple as it could be:
```php
try
{
    $confirm = new Confirmation($__GET);
}
catch (InvalidArgumentException $e)
{
    // do what you have to do if the call is not valid
}
```
For confirmation URLs that may have other get parameters already include you can do a cleanup:
```php
try
{
    $confirm = new Confirmation($__GET, true);
}
catch (InvalidArgumentException $e)
{
    // do what you have to do if the call is not valid
}
```
The clean Up can also be called static
```php
$onlyMPay24Paramter = Confirmation::cleanUpArray($__GET);
$confirm = new Confirmation($onlyMPay24Paramter);
```
Now you have also access to the values
```php
$mpay24tip = $confirm->MPAYTID;
$status    = $confirm->STATUS;
$tid       = $confirm->TID;
```
This are the valid parameters as var  as I know it:

```
TYPE:   PARAMETER      - VALUE(s)

STRING: OPERATION      - CONFIRMATION
STRING: TID            - length <= 32
STRING: STATUS         - RESERVED, BILLED, REVERSED, CREDITED, ERROR
INT:    PRICE          - length = 11 (e. g. "10" = "0,10")
STRING: CURRENCY       - length = 3 (ISO currency code, e. g. "EUR")
STRING: P_TYPE         - CC, ELV, EPS, GIROPAY, MAESTRO, PB, PSC, QUICK
STRING: BRAND          - AMEX, DINERS, JCB, MASTERCARD, VISA, ATOS, HOBEX-AT, HOBEX-DE
INT:    MPAYTID        - length = 11
STRING: USER_FIELD
STRING: ORDERDESC
STRING: CUSTOMER
STRING: CUSTOMER_EMAIL
STRING: LANGUAGE       - length = 2
STRING: CUSTOMER_ID    - length = 11
STRING: PROFILE_ID     -
STRING: PROFILE_STATUS - IGNORED, USED, ERROR, CREATED, UPDATED, DELETED
STRING: FILTER_STATUS
STRING: APPR_CODE
```

**Comment by tobiaslins** [comment]
@stefanpolzer great work!
The parameter validation is not completed but we are going to add the missing ones!

**Comment by stefanpolzer** [comment]
The Value validation is done by RegEx /^ for the start and $/ for the and will always be include
No is_numeric() or strln() functions ... very easy to extend and maintained

**Comment by tobiaslins** [comment]
@stefanpolzer yes, that is good, i meant, that for example some brand's are missing!

**Pull request merged**
