### PR TITLE
small improvements in usability

### PR DESCRIPTION
**Pull request by netbull**
proposal for #32 
- the config object is mandatory to avoid confusion
- the config object have all available arguments in the constructor for better understanding what to expect -> direct hints from IDE's

### CODE REVIEW

**Comment by stefanpolzer** [comment]
This commit breaks backward compatibility!!!

**Comment by stefanpolzer** [comment]
This commit break backward Compatibility!!!
Just add A docblock if you want to have direct hint in your IDE

**Comment by stefanpolzer** [comment]
@netbull the Constructor will cause an Exception... 9**** is not a Valid ID, change it to 90000 of 91234

**Comment by tobiaslins** [comment]
we can close this PR now - as it is not required anymore?
Am I right @netbull ?

**Comment by netbull** [comment]
@tobiaslins still I'm in favour to either force using the Config object or to avoid using it, but it's up to you, like @stefanpolzer wrote is business decision.

**Comment by tobiaslins** [comment]
@netbull 
We will keep the old version (config file, constructor) and the new option with the mpy24config class!
We think it is a good way to be compatible with our old implementations & allow people to configure their sdk the new way (for business needs like the one from @stefanpolzer )

But thanks a lot for contributing! :)

**Comment by netbull** [comment]
@tobiaslins that's fine, just make sure the SDK to be clean and easy to use, not to follow Apps with bad design.

**Pull request closed without merging**
