### PR TITLE
Refector response classes to fit SOAP name and functionality

### PR DESCRIPTION
**Pull request by stefanpolzer**

### CODE REVIEW

**Comment by stefanpolzer** [comment]
@tobiaslins this commit seam to be a good base to merge the hole stuff into master.
Of course come SOAP functionality is not yet implemented, but it is not in the master brach either.
What do you think is the time frame, or do you plan to implement more before going productive?

**Comment by netbull** [comment]
+1 for the new release.

I saw @stefanpolzer made a plugin for laravel and I made a bundle for Symfony, so it will be good to add the SDK finally as dependency.

**Comment by stefanpolzer** [comment]
@netbull as so as the new release is public I will adapt the Laravel plugin and include the mpay24-php package as dependency. I hope this will be soon ;-)
@tobiaslins If mPAY24 want so make a official fork of it, I'm happy if you do so! @tobiaslins

**Comment by tobiaslins** [comment]
thank you!
@stefanpolzer @netbull I think that we can merge this branch now into master and create the new release :)

**Comment by stefanpolzer** [comment]
@tobiaslins what do you think about PHP [traits](http://php.net/manual/de/language.oop5.traits.php),
I have the Idea to use it for some of the Response class so that some code can be reused.
e.g. checking for optional Fields but this would change the minimum requirement to PHP 5.4

**Pull request merged**
