### PR TITLE
Initial version 5.0.0

### PR DESCRIPTION
**Pull request by stefanpolzer**
Mark the MDXI schema validation as deprecated and remove all internal usages... validation is now only made by the mpay24 system that will return an error if needed.

### CODE REVIEW

**Comment by mdaskalov** [comment]
Thanks, seems that we have almost the same solution... Please have a look over my pull request. I think we can merge both PR.

**Comment by mdaskalov** [comment]
Could you please confirm that the `errNo` and `errText` are properly set in error case (`status` is set to `ERROR` in SOAP response).
If so I will merge this and drop the branch `remove-mdxi-validation` for this release.

**Comment by stefanpolzer** [comment]
Last travis CI Build was passing: https://travis-ci.org/mpay24/mpay24-php/builds/480561077

**Comment by stefanpolzer** [comment]
Last travis CI Build was passing: https://travis-ci.org/mpay24/mpay24-php/builds/480620973

**Comment by stefanpolzer** [comment]
Fixing #74

**Comment by stefanpolzer** [comment]
Fixing #86

**Comment by stefanpolzer** [comment]
I thing I have 7 out of the 10 open issues fixed with this PR including the other open PR #88
@zirnipa @mdaskalov could you test this PR?!?

**Comment by mdaskalov** [comment]
Tested:

**Comment by stefanpolzer** [comment]
Fixing #92

**Comment by zirnipa** [comment]
**Testing**
/examples/checkout.php 

throws following error:

`Warning: DOMDocument::createElement() expects parameter 2 to be string, object given in /home/.sites/121/site2476779/web/work/500/src/Mpay24Order.php on line 163 Fatal error: Uncaught TypeError: Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given in /home/.sites/121/site2476779/web/work/500/src/Mpay24Order.php:164 Stack trace: #0 /home/.sites/121/site2476779/web/work/500/src/Mpay24Order.php(164): DOMNode->appendChild(NULL) #1 /home/.sites/121/site2476779/web/work/500/examples/checkout.php(10): Mpay24\Mpay24Order->__set('Tid', Object(DOMText)) #2 {main} thrown in /home/.sites/121/site2476779/web/work/500/src/Mpay24Order.php on line 164`

**Comment by zirnipa** [comment]
Tests passed.

Thank you for your work and support @stefanpolzer

**Comment by stefanpolzer** [comment]
The last commit is to add phpstan support as requested in #93
No code change was made, only a autoload file for test are added and a lot of PHPDoc are changed.

**Pull request merged**
