### PR TITLE
Mistake in Mpay24Order class

### PR DESCRIPTION
**Pull request by PandaHugMonster**
MPay24Order instead of Mpay24Order.
PSR-4 autoloading in composer under linux didn't work.

### CODE REVIEW

**Comment by stefanpolzer** [comment]
You did merge a complete old code base with the new one... the Read me have text like "It's unofficial fork!"
We should this be part of the official code?

I recommend that you bing your fork to the same state as the last [mpay24 master branch](https://github.com/mpay24/mpay24-php/commit/18f4de7c705515e7997eff3b4ee159e3afc1ac31) and go on form there.

**Comment by stefanpolzer** [comment]
Created a new PR #53

**Comment by PandaHugMonster** [comment]
No probs, will no longer notify about your mistakes next time!
Good luck!

**Comment by stefanpolzer** [comment]
@PandaHugMonster, opening a Issue with is very welcome, but asking for a pull request where you fix one thing and  break other things that are all right, is something differed IMHO.
e.g. your composer.json will break things completely.

I'm sorry and I apologize for any misunderstanding.

**Pull request closed without merging**
